name: Deploy WebApp to AWS and GCP

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Integration Tests with MySQL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Start MySQL Service
        run: |
          echo "Starting MySQL..."
          sudo systemctl start mysql
          sudo systemctl status mysql || true
          mysql --version

      - name: Set Up MySQL Database and User
        run: |
          echo "Restarting MySQL..."
          sudo systemctl restart mysql

          echo "Creating database and user..."
          mysql -u root -e "CREATE DATABASE IF NOT EXISTS \\`${{ secrets.MYSQL_DATABASE }}\\`;"
          mysql -u root -e "CREATE USER IF NOT EXISTS '${{ secrets.MYSQL_USER }}'@'%' IDENTIFIED BY '${{ secrets.MYSQL_PASSWORD }}';"
          mysql -u root -e "GRANT ALL PRIVILEGES ON \\`${{ secrets.MYSQL_DATABASE }}\\`.* TO '${{ secrets.MYSQL_USER }}'@'%';"
          mysql -u root -e "FLUSH PRIVILEGES;"

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Run Integration Tests
        env:
          DB_NAME: ${{ secrets.MYSQL_DATABASE }}
          DB_USER: ${{ secrets.MYSQL_USER }}
          DB_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_DIALECT: ${{ secrets.DB_DIALECT }}
        run: NODE_ENV=test npm test

  build:
    name: Build Application Artifact
    needs: test 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Create .env file
        run: |
          echo "DB_NAME=${{ secrets.MYSQL_DATABASE }}" > .env
          echo "DB_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_DIALECT=${{ secrets.DB_DIALECT }}" >> .env

      - name: Build Artifact
        run: zip -r webapp.zip .

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: webapp-artifact
          path: webapp.zip

  packer-build:
    name: Build Custom Image for AWS & GCP
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: webapp-artifact

      - name: Install Packer
        uses: hashicorp/setup-packer@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up GCP CLI
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Build Custom Image with Packer
        run: |
          ls -lah  # Verify webapp.zip exists
          packer init packer_image/
          packer validate packer_image/
          packer build packer_image/

      - name: Share AWS Image
        run: |
          AMI_ID=$(aws ec2 describe-images \
          --owners self \
          --filters "Name=state,Values=available" \
            --query "Images | sort_by(@, &CreationDate)[-1].ImageId" \
                --output text)
  
          if [ -n "$AMI_ID" ]; then
            echo "Sharing AMI $AMI_ID with AWS DEMO account..."
            aws ec2 modify-image-attribute --image-id "$AMI_ID" \
              --launch-permission '{"Add": [{"UserId": "${{ secrets.AWS_DEMO_ACCOUNT_ID }}"}]}'
          else
            echo "AMI not found, exiting."
            exit 1
          fi
