name: Packer CI

on:
  pull_request:
    branches:
      - main

jobs:
  packer-build:
    name: Packer Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"

      - name: Create `webapp.zip`
        run: |
          zip -r webapp.zip .
        shell: bash

      - name: Create .env file
        run: |
          echo "DB_NAME=${{ secrets.MYSQL_DATABASE }}" > .env
          echo "DB_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_DIALECT=${{ secrets.DB_DIALECT }}" >> .env
          echo AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }} >> .env
          echo AWS_REGION: ${{ secrets.AWS_REGION }} >> .env    
      - name: Initialize Packer
        id: init
        run: packer init .

      - name: Check Packer Formatting
        id: fmt
        run: packer fmt -check aws-ubuntu.pkr.hcl

      - name: Validate Packer Template
        id: validate
        run: packer validate aws-ubuntu.pkr.hcl
        shell: bash