name: Packer CI

on:
  pull_request:
    branches:
      - main

jobs:
  packer-build:
    name: Packer Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"

      - name: Create `webapp.zip`
        run: |
          zip -r webapp.zip .
        shell: bash

      - name: Initialize Packer
        id: init
        run: packer init .

      - name: Check Packer Formatting
        id: fmt
        run: packer fmt -check aws-ubuntu.pkr.hcl

      - name: Validate Packer Template
        id: validate
        run: packer validate aws-ubuntu.pkr.hcl
        shell: bash
        env:
          DB_NAME: ${{ secrets.MYSQL_DATABASE }}
          DB_USER: ${{ secrets.MYSQL_USER }}
          DB_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_DIALECT: ${{ secrets.DB_DIALECT }}
          AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}