name: Deploy WebApp to AWS

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Integration Tests with MySQL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Start MySQL Service
        run: |
          echo "Starting MySQL..."
          sudo systemctl start mysql
          sudo systemctl status mysql || true
          mysql --version

      - name: Set Up MySQL Database and User
        run: |
          echo "Restarting MySQL..."
          sudo systemctl restart mysql

          echo "Creating database and user..."
          mysql --user=${{ secrets.MYSQL_USER }} --password=${{ secrets.MYSQL_PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS \`${{ secrets.MYSQL_DATABASE }}\`;"
          mysql --user=${{ secrets.MYSQL_USER }} --password=${{ secrets.MYSQL_PASSWORD }} -e "CREATE USER '${{ secrets.MYSQL_USER }}'@'%' IDENTIFIED BY '${{ secrets.MYSQL_PASSWORD }}';"
          mysql --user=${{ secrets.MYSQL_USER }} --password=${{ secrets.MYSQL_PASSWORD }} -e "GRANT ALL PRIVILEGES ON \`${{ secrets.MYSQL_DATABASE }}\`.* TO '${{ secrets.MYSQL_USER }}'@'%';"
          mysql --user=${{ secrets.MYSQL_USER }} --password=${{ secrets.MYSQL_PASSWORD }} -e "FLUSH PRIVILEGES;"

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Dependencies
        run: |
          npm ci
          npm install multer multer-s3 dotenv --save

      - name: Create .env file
        run: |
          echo "DB_NAME=${{ secrets.MYSQL_DATABASE }}" > .env
          echo "DB_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_DIALECT=${{ secrets.DB_DIALECT }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo PORT: ${{ secrets.PORT }} >> .env
          echo AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }} >> .env
          echo AWS_REGION: ${{ secrets.AWS_REGION }} >> .env

      - name: Run Integration Tests
        env:
          DB_NAME: ${{ secrets.MYSQL_DATABASE }}
          DB_USER: ${{ secrets.MYSQL_USER }}
          DB_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_DIALECT: ${{ secrets.DB_DIALECT }}
          DB_PORT: ${{ secrets.DB_PORT }}
          PORT: ${{ secrets.PORT }}
          AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: NODE_ENV=test npm test

  packer-build:
    name: Build Custom Image for AWS & GCP
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Packer
        run: |
          curl -LO https://releases.hashicorp.com/packer/1.11.2/packer_1.11.2_linux_amd64.zip
          unzip packer_1.11.2_linux_amd64.zip
          sudo mv packer /usr/local/bin/
          packer --version

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create and populate .env
        run: |
          touch .env
        shell: bash

      - name: Create webapp.zip from existing directory
        run: |
          zip -r webapp.zip .
        shell: bash

      - name: Run `packer init`
        id: init
        run: packer init .

      - name: Run `packer validate`
        id: validate
        run: packer validate .

      - name: Run `packer build` 
        id: build
        run: packer build aws-ubuntu.pkr.hcl

      - name: share image in aws
        run: |
          AMI_ID=$(aws ec2 describe-images \
            --owners self \
            --filters "Name=state,Values=available" \
            --query "Images | sort_by(@, &CreationDate)[-1].ImageId" \
            --output text)
          echo "AMI ID: $AMI_ID"
          echo "AMI ID: $AMI_ID"
          echo "AMI_ID=$AMI_ID" >> $GITHUB_ENV

          if [ -n "$AMI_ID" ]; then
            echo "Sharing AMI $AMI_ID with AWS DEMO account..."
            aws ec2 modify-image-attribute --image-id "$AMI_ID" \
              --launch-permission "{\"Add\": [{\"UserId\": \"${{ secrets.AWS_DEMO_ACCOUNT_ID }}\"}]}"
          else
            echo "AMI not found, exiting."
            exit 1
          fi

      #steps 1: configure Demo account AWS credentials
      - name: Reconfigure github runner to demo account
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.DEMO_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEMO_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      #steps 2: create a new launch template version
      - name: Create new launch template
        run: |
              AMI_ID=${{ env.AMI_ID }}
              echo "Creating new launch template version with AMI ID: $AMI_ID"
              aws ec2 create-launch-template-version --launch-template-id ${{secrets.LAUNCH_TEMPLATE_ID}} --version-description "New version with latest AMI" --source-version 1 --launch-template-data "ImageId=$AMI_ID"

      # Step 3: Start Instance Refresh for Auto Scaling Group
      - name: Start Instance Refresh
        id: start_refresh
        run: |
          REFRESH_ID=$(aws autoscaling start-instance-refresh \
              --auto-scaling-group-name ${{ secrets.AUTO_SCALING_GROUP_NAME }} \
              --query "InstanceRefreshId" \
              --output text \
              --no-cli-pager)
          echo "Instance Refresh started with ID: $REFRESH_ID"
          echo "INSTANCE_REFRESH_ID=$REFRESH_ID" >> $GITHUB_ENV

      # Step 4: Wait for Instance Refresh to Complete
      - name: Wait for Instance Refresh Completion
        run: |
          echo "Waiting for instance refresh to complete..."
          while true; do
            STATUS=$(aws autoscaling describe-instance-refreshes \
                --auto-scaling-group-name ${{ secrets.AUTO_SCALING_GROUP_NAME }} \
                --query "InstanceRefreshes[?InstanceRefreshId=='${{ env.INSTANCE_REFRESH_ID }}'].Status" \
                --output text \
                --no-cli-pager)
            echo "Current status: $STATUS"
            if [[ "$STATUS" == "Successful" ]]; then
              echo "Instance Refresh completed successfully."
              break
            elif [[ "$STATUS" == "Failed" || "$STATUS" == "Cancelled" ]]; then
              echo "Instance Refresh failed or was cancelled. Exiting."
              exit 1
            fi
            sleep 30
          done