name: webapp CI - API Tests with MySQL

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run API Tests with MySQL
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start MySQL Service # Start the servive
        run: |
          sudo systemctl start mysql
          sudo systemctl status mysql || true  # Show MySQL status for debugging
          mysql --version  # Verify MySQL installation

          - name: Set Up MySQL Database and User
          run: |
            sudo systemctl restart mysql  # Ensure MySQL service is running
            mysql --user=${{ secrets.MYSQL_USER }} --password=${{ secrets.MYSQL_PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.MYSQL_DATABASE }};"
            mysql --user=${{ secrets.MYSQL_USER }} --password=${{ secrets.MYSQL_PASSWORD }} -e "GRANT ALL PRIVILEGES ON ${{ secrets.MYSQL_DATABASE }}.* TO '${{ secrets.MYSQL_USER }}'@'localhost' WITH GRANT OPTION;"
            mysql --user=${{ secrets.MYSQL_USER }} --password=${{ secrets.MYSQL_PASSWORD }} -e "FLUSH PRIVILEGES;"
        

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Run API Tests
        run: NODE_ENV=test npm test
