name: webapp CI - API Tests with MySQL

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run API Tests with MySQL
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start MySQL Service
        run: |
          echo "Starting MySQL..."
          sudo systemctl start mysql
          sudo systemctl status mysql || true  # Show MySQL status for debugging
          mysql --version  # Verify MySQL installation

      - name: Set Up MySQL Database and User
        run: |
          echo "Restarting MySQL..."
          sudo systemctl restart mysql  # Ensure MySQL service is running

          echo "Creating database and user..."
          mysql --user=${{ secrets.MYSQL_USER }} --password=${{ secrets.MYSQL_PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS \`${{ secrets.MYSQL_DATABASE }}\`;"
          mysql --user=${{ secrets.MYSQL_USER }} --password=${{ secrets.MYSQL_PASSWORD }} -e "CREATE USER IF NOT EXISTS '${{ secrets.MYSQL_USER }}'@'%' IDENTIFIED BY '${{ secrets.MYSQL_PASSWORD }}';"
          mysql --user=${{ secrets.MYSQL_USER }} --password=${{ secrets.MYSQL_PASSWORD }} -e "GRANT ALL PRIVILEGES ON \`${{ secrets.MYSQL_DATABASE }}\`.* TO '${{ secrets.MYSQL_USER }}'@'%' WITH GRANT OPTION;"
          mysql --user=${{ secrets.MYSQL_USER }} --password=${{ secrets.MYSQL_PASSWORD }} -e "FLUSH PRIVILEGES;"

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Dependencies
        run: |
          npm ci
          npm install dotenv --save

      - name: Verify Environment Variables
        run: |
          echo "Verifying environment variables..."
          echo "DB_NAME=${{ secrets.MYSQL_DATABASE }}"
          echo "DB_USER=${{ secrets.MYSQL_USER }}"
          echo "DB_PASSWORD=${{ secrets.MYSQL_PASSWORD }}"
          echo "DB_HOST=localhost"
          echo "DIALECT=mysql"

      - name: Run API Tests
        env:
          DB_NAME: ${{ secrets.MYSQL_DATABASE }}
          DB_USER: ${{ secrets.MYSQL_USER }}
          DB_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          DB_HOST: "127.0.0.1"
          DB_DIALECT: "mysql"
          NODE_ENV: "test"
        run: |
          echo "Running API Tests..."
          npm test
